# Generated by Django 5.1.5 on 2025-01-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='salaryadvance',
            name='employee',
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='SalaryAdvance',
        ),
    ]
