# Generated by Django 5.1.5 on 2025-01-30 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="User's first name.", max_length=50)),
                ('last_name', models.CharField(help_text="User's last name.", max_length=50)),
                ('email', models.EmailField(help_text="User's email address.", max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number.', max_length=15, null=True)),
                ('address', models.TextField(blank=True, help_text="User's residential address.", null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile picture of the user.', null=True, upload_to='profile_pictures/')),
                ('hire_date', models.DateField(blank=True, help_text='Date of hire.', null=True)),
                ('department', models.CharField(blank=True, choices=[('IT', 'IT'), ('Operations', 'Operations'), ('HR', 'HR')], help_text="User's department in the organization.", max_length=50, null=True)),
                ('position', models.CharField(blank=True, choices=[('Manager', 'Manager'), ('Developer', 'Developer'), ('HR', 'HR'), ('Sales', 'Sales')], help_text='Position held by the user.', max_length=50, null=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, help_text='Salary of the user.', max_digits=10)),
                ('is_admin', models.BooleanField(default=False, help_text='Indicates if the user has admin privileges.')),
                ('user', models.ForeignKey(help_text='Link to the related user account.', on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
    ]
