# Generated by Django 5.1.5 on 2025-02-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_profile_address_profile_nhima_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nhima_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ssn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tpin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
