# Generated by Django 5.1.5 on 2025-02-08 10:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_passwordrestetoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PasswordResteToken',
            new_name='PasswordRestToken',
        ),
    ]
