# Generated by Django 5.1.5 on 2025-02-08 10:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_passwordrestetoken_passwordresttoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PasswordRestToken',
            new_name='PasswordResetToken',
        ),
    ]
