# Generated by Django 5.1.5 on 2025-01-30 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profile_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('leave_type', models.CharField(choices=[('Vacation', 'Vacation'), ('Leave', 'Leave'), ('Bereavement', 'Bereavement'), ('Paternity', 'Paternity'), ('Maternity', 'Maternity'), ('Time Off with Pay', 'Time Off with Pay'), ('Others', 'Others')], default='Others', max_length=50)),
                ('hr_approved', models.BooleanField(default=False)),
                ('director_approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
